[programs.devnet]
myepicproject = "GTxHy9wVzoPDPoMmSWiX74GPctQcKZvrfaW6L2ZCQeT7"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/abhi/.config/solana/id.json"

[scripts]
test =  "node tests/myepicproject.js"